logging:
  file:
    name: log/LotteON.log
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    org:
      hibernate: info
      springframework:
        security: debug
    root: info
server:
  servlet:
    context-path: /LotteON

spring:
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: extendsabstractclass # 3
    password: hfrezhsvhiitsckb # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: lotteON3!
    url: jdbc:mysql://3.25.162.104:3306/LotteON
    username: lotteON3
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  jpa:
    database: mysql
    hibernate:
      # 배포할 때는 반드시 none, 개발할 때는 가급적 update
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates


  servlet:
    multipart:
      location: src/main/resources/static/file/
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
